<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SHWETHA-PC-15S" failures="1" tests="1" name="Test-Edge(failed)" time="18.087" errors="0" timestamp="2025-03-13T09:28:01 IST">
  <testcase classname="testCases.LoginTest" name="testSuccessfulLogin" time="10.108">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.LoginTest.testSuccessfulLogin(LoginTest.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testSuccessfulLogin -->
</testsuite> <!-- Test-Edge(failed) -->
